<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="generator" content="pandoc" />


<meta name="author" content="Matthias Schmitt" />


<title>Reproducible Research: Analyzing activity patterns</title>

<script src="PA1_template_files/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="PA1_template_files/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="PA1_template_files/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="PA1_template_files/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="PA1_template_files/navigation-1.1/tabsets.js"></script>
<link href="PA1_template_files/highlightjs-1.1/default.css" rel="stylesheet" />
<script src="PA1_template_files/highlightjs-1.1/highlight.js"></script>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs && document.readyState && document.readyState === "complete") {
   window.setTimeout(function() {
      hljs.initHighlighting();
   }, 0);
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>


</head>

<body>

<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
  height: auto;
}
.tabbed-pane {
  padding-top: 12px;
}
button.code-folding-btn:focus {
  outline: none;
}
</style>



<div class="container-fluid main-container">

<!-- tabsets -->
<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});
</script>

<!-- code folding -->






<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Reproducible Research: Analyzing activity patterns</h1>
<h4 class="author"><em>Matthias Schmitt</em></h4>
<h4 class="date"><em>14 Januar 2017</em></h4>

</div>


<div id="project-goal-data-setup" class="section level2">
<h2>Project goal &amp; data setup</h2>
<p>As described on the course website, we use ‘’data from a personal activity monitoring device. This device collects data at 5 minute intervals through out the day. The data consists of two months of data from an anonymous individual collected during the months of October and November, 2012 and include the number of steps taken in 5 minute intervals each day.’’ We analyze a set of questions related to activity patterns in the data, especially the difference between weekdays and weekends. We first read the data:</p>
<pre class="r"><code># for local data file
# activity &lt;- read.csv(&quot;D:/Documents/R/data-science/reproducible/activity.csv&quot;)

# auto-download from web source
temp &lt;- tempfile()
download.file(&quot;http://d396qusza40orc.cloudfront.net/repdata%2Fdata%2Factivity.zip&quot;,temp)
unzip(temp)
unlink(temp)

activity &lt;- read.csv(&quot;activity.csv&quot;)</code></pre>
<p>Since we need to work with the <em>date</em> variable a lot later, we transform it here, and introduce the flag <em>isWeekend</em>, which we need later to analyse patterns on weekends separately from those during the week.</p>
<pre class="r"><code>activity$date &lt;- as.Date(activity$date)

# there&#39;s a base R function for getting the weekdays, but I use the lubridate version
# to make it work on all locales (I have a non-US locale windows OS)
activity$wday &lt;- wday(activity$date, label=TRUE)
activity$isWeekend &lt;- activity$wday %in% c(&quot;Sat&quot;, &quot;Sun&quot;)</code></pre>
</div>
<div id="total-number-of-steps-taken-each-day" class="section level2">
<h2>Total number of steps taken each day</h2>
<p>We aggregate the number of steps for each date in the data set, and distinguish between weekend and weekday for each day:</p>
<pre class="r"><code>steps_per_day &lt;- aggregate(steps ~ date+isWeekend, activity, sum)</code></pre>
<p>Let’s explore this as a time series - this was not requested, but it’s informative:</p>
<pre class="r"><code>ggplot(steps_per_day, aes(x=date, y=steps, fill=isWeekend)) + geom_bar(stat=&quot;identity&quot;) + labs(x=&quot;Date&quot;, y=&quot;# of steps&quot;) + scale_x_date()</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-4-1.png" /><!-- --></p>
<p>For some days there seems to be no activity at all, which is quite implausible. We’re therefore tasked to impute activity data for those dates. We’ll address that below, first we plot the requested histogram of steps taken per day:</p>
<pre class="r"><code>ggplot(steps_per_day, aes(steps, fill=isWeekend)) + geom_histogram(bins = 20) + labs(x=&quot;# of steps&quot;, y=&quot;# of days&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-5-1.png" /><!-- --></p>
</div>
<div id="mean-and-median-number-of-steps-taken-each-day" class="section level2">
<h2>Mean and median number of steps taken each day</h2>
<pre class="r"><code># use summary table 
summary(steps_per_day)</code></pre>
<pre><code>##       date            isWeekend           steps      
##  Min.   :2012-10-02   Mode :logical   Min.   :   41  
##  1st Qu.:2012-10-16   FALSE:39        1st Qu.: 8841  
##  Median :2012-10-29   TRUE :14        Median :10765  
##  Mean   :2012-10-30   NA&#39;s :0         Mean   :10766  
##  3rd Qu.:2012-11-16                   3rd Qu.:13294  
##  Max.   :2012-11-29                   Max.   :21194</code></pre>
<pre class="r"><code># ... or alternatively we could use mean() and median() 
mean(steps_per_day$steps)</code></pre>
<pre><code>## [1] 10766.19</code></pre>
<pre class="r"><code>median(steps_per_day$steps)</code></pre>
<pre><code>## [1] 10765</code></pre>
<p>The mean is 10766 steps per day, the median is 10765 steps per day.</p>
</div>
<div id="time-series-of-the-average-number-of-steps-taken" class="section level2">
<h2>Time series of the average number of steps taken</h2>
<p>We now focus on the within-day pattern (intervals during the day) and average over all dates in the dataset.</p>
<pre class="r"><code>steps_per_interval &lt;- aggregate(steps ~ interval, activity, mean)
ggplot(steps_per_interval, aes(x=interval, y=steps)) + geom_line()+ labs(x=&quot;time interval&quot;, y=&quot;# of steps&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-7-1.png" /><!-- --></p>
<p>The 5-minute interval that, on average, contains the maximum number of steps is</p>
<pre class="r"><code>highest_activity &lt;- steps_per_interval[which.max(steps_per_interval$steps),]
print(highest_activity)</code></pre>
<pre><code>##     interval    steps
## 104      835 206.1698</code></pre>
</div>
<div id="imputing-missing-data" class="section level2">
<h2>Imputing missing data</h2>
<p>Above we saw that on some dates no steps were measured at all.</p>
<pre class="r"><code>nrow(activity[is.na(activity$steps),])</code></pre>
<pre><code>## [1] 2304</code></pre>
<p>Whatever the reason for the 2304 missing rows (maybe the owner forgot to switch the device on), we’re tasked to impute data for the dates were no steps were measured. Because activity patterns differ between weekend and weekday (shown below in detail), we’re careful to impute a separate data point for each day of the week separately. We compute the mean of all the 5min interval for each day of the week and aggregate.</p>
<pre class="r"><code>steps_per_wday &lt;- aggregate(steps ~ interval+wday, activity, mean)
steps_per_wday &lt;- rename(steps_per_wday, c(&quot;steps&quot;=&quot;imputed_steps&quot;))

head(steps_per_wday)</code></pre>
<pre><code>##   interval wday imputed_steps
## 1        0  Sun      0.000000
## 2        5  Sun      0.000000
## 3       10  Sun      0.000000
## 4       15  Sun      0.000000
## 5       20  Sun      0.000000
## 6       25  Sun      7.428571</code></pre>
<pre class="r"><code># we now have a list of all (intervals, weekdays) with the associated mean number of steps for
# e.g. a &quot;typical Monday interval No. 100&quot;! Join that to the data:

activity_imputed &lt;- merge(activity, steps_per_wday, all.x=TRUE, by=c(&quot;interval&quot;, &quot;wday&quot;))
activity_imputed$steps &lt;- ifelse(is.na(activity_imputed$steps), activity_imputed$imputed_steps, activity_imputed$steps)
activity_imputed$isImputed &lt;- activity_imputed$imputed_steps == activity_imputed$steps

steps_per_day.imputed &lt;- aggregate(steps ~ date+isImputed, activity_imputed, sum)
# Due to the working of aggregate, after this step we have entries where 
# (sum_of_imputed_steps == 0 &amp; isImputed = TRUE) =&gt; eliminate those where we have imputed zero steps!

steps_per_day.imputed &lt;- steps_per_day.imputed[which(!(steps_per_day.imputed$steps == 0 &amp;                                                                       steps_per_day.imputed$isImputed)),]</code></pre>
<p>The time series now looks as follows:</p>
<pre class="r"><code>ggplot(steps_per_day.imputed, aes(x=date, y=steps, fill=isImputed)) + geom_bar(stat=&quot;identity&quot;) + labs(x=&quot;Date&quot;, y=&quot;# of steps&quot;) + scale_x_date()</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-11-1.png" /><!-- --></p>
<p>which is quite plausible, except for Nov 15th. We check why no data was imputed, and it turns out that the step variable is 0 rather than NA for all but 2 of the intervals that day:</p>
<pre class="r"><code>num_of_intervals_zero &lt;- length(which(activity$date==&quot;2012-11-15&quot; &amp; activity$steps ==0))
num_of_intervals_total &lt;- length(which(activity$date==&quot;2012-11-15&quot;))
print(num_of_intervals_total-num_of_intervals_zero)</code></pre>
<pre><code>## [1] 2</code></pre>
<p>The histogram of the total number of steps taken each day after missing values are imputed is as follows:</p>
<pre class="r"><code>ggplot(steps_per_day.imputed, aes(steps, fill=isImputed)) + geom_histogram(breaks=seq(1, 24000, by = 2000)) + labs(x=&quot;# of steps&quot;, y=&quot;# of days&quot;)</code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-13-1.png" /><!-- --></p>
<p>We report the mean and median total number of steps taken per day after imputation:</p>
<pre class="r"><code>steps_per_day.by_date &lt;- aggregate(steps ~ date, activity_imputed, sum)
mean(steps_per_day.by_date$steps)</code></pre>
<pre><code>## [1] 10821.21</code></pre>
<pre class="r"><code>median(steps_per_day.by_date$steps)</code></pre>
<pre><code>## [1] 11015</code></pre>
<p>After imputation the mean is 10821 steps compared to 10766 steps before imputation. The median has moved stronger, from 10765 before imputation to 11015 steps. The shape of the distribution remains basically unchanged.</p>
</div>
<div id="comparison-of-activity-pattern-on-weekdays-versus-weekend" class="section level2">
<h2>Comparison of activity pattern on weekdays versus weekend</h2>
<p>Last but not least we’re tasked to compare the average number of steps taken per 5-minute interval across weekdays and weekends in a time series plot:</p>
<pre class="r"><code>steps_per_interval &lt;- aggregate(steps ~ interval+isWeekend, activity, mean)
ggplot(steps_per_interval, aes(x=interval, y=steps)) + geom_line() + labs(x=&quot;time interval&quot;, y=&quot;# of steps&quot;) + facet_grid(isWeekend ~ .,  labeller = as_labeller(c(&#39;FALSE&#39;=&quot;Weekday&quot;, &#39;TRUE&#39;=&quot;Weekend&quot;))) </code></pre>
<p><img src="PA1_template_files/figure-html/unnamed-chunk-15-1.png" /><!-- --></p>
<p>On weekdays there’s a clear peak in activity around interval 800, after which activity is reduced. On weekends activity is more distributed, without a clear peak. Overall, activity is higher on weekends than on weekdays.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.header').parent('thead').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
